language: csharp
mono: none
dotnet: 1.0.1
sudo: required
dist: trusty

addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/14.04/prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - powershell

script:
  powershell scripts/build.ps1